name: PR Workflow
on: push

jobs:
  verify-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Install nodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
